### PR TITLE
Enable selection of installed LuCI themes

### PR DESCRIPTION
**Pull request by DaveA-W**
Coded installed theme display and selection based on investigations at http://itus.accessinnov.com/LuCI-Themes-tp435p662.html 

Later compared to system.lua within Cavium OpenWrt (not far off the mark!) and updated the label to match.

### CODE REVIEW

**Comment by DaveA-W** [comment]
Hi @HansTo, rather than merge myself, thought I'd give you a chance to review & merge.
Cheers, Dave (a.k.a. gnomad)

**Comment by DaveA-W** [comment]
Hi @Roadrunneruk, if you've installed the material them package, do you want to give this a whirl?
Feel free to merge into master if you're happy - it allows users to switch between themes on the Admin:System:System page, under the Language & Style tab.

**Comment by Roadrunneruk** [comment]
Hi DaveA-W
I'm new to Github,  do I have to copy and paste the whole file from Github or can i just download the whole file?
 usr/lib/lua/luci/model/cbi/admin_system/system.lua

**Comment by DaveA-W** [comment]
Hi @Roadrunneruk, 
- Click the "Files Changed" tab at the top of the pull request.
- Click the monitor icon top-right to open the file in GitHub Desktop (if you have it installed). Or;
- Click "View" top right, then "Raw" to download.

**Comment by user8446** [comment]
It came right up after these commands you posted in the forum:

uci set luci.main.mediaurlbase='/luci-static/material'
uci commit luci

It's nice to now have the option to switch it in the GUI!

**Pull request merged**
